In [27]:
import torch
import numpy as np

input = np.array(
[[[
    [1  ,1,0,0,0,1],
    [1  ,1,0,1,0,1],
    [0.5,1,1,1,0,0],
    [0  ,1,0,1,0,1],
    [0  ,1,1,0,0,1],
    [1  ,0,1,0,0,0],
]
],
    [[
    [1  ,1,0,0,0,1],
    [1  ,1,0,1,0,1],
    [0.5,1,1,1,0,0],
    [0  ,1,0,1,0,1],
    [0  ,1,1,0,0,1],
    [1  ,0,1,0,0,0],
]
]
]
)

kernel = np.transpose(np.array(
[[[
    [1,1,1,1,1,1.0],
    [1,1,1,1,1,1]
]]]),[0,1,2,3])

In [42]:
# One image of one feature map 6x6
# The kernel has 1 feature map out, 1 feature map in, 2 vectors of size 6
input.shape,kernel.shape

((2, 1, 6, 6), (1, 1, 2, 6))

In [43]:
input_torch = torch.FloatTensor(input)
kernel_torch = torch.FloatTensor(kernel)

In [44]:
import torch.nn.functional as F
import torch.nn
from torch.autograd import Variable
cnn = torch.nn.Conv2d(1,1,(1,6),bias=False)
cnn.weight.data.copy_(kernel_torch[:,:,0,:])
a = cnn.forward(Variable(input_torch))
print(a.size())

torch.Size([2, 1, 6, 1])


In [56]:
cnn2 = torch.nn.Conv2d(1,1,(6,1),bias=False)
cnn2.weight.data.copy_(kernel_torch[:,:,0,:])

b = cnn2.forward(Variable(input_torch))
print(b.size())

RuntimeError: The expanded size of the tensor (1) must match the existing size (6) at non-singleton dimension 3

In [14]:
a

tensor([[[[ 3.0000],
          [ 4.0000],
          [ 3.5000],
          [ 3.0000],
          [ 3.0000],
          [ 2.0000]]],


        [[[ 3.0000],
          [ 4.0000],
          [ 3.5000],
          [ 3.0000],
          [ 3.0000],
          [ 2.0000]]]])

In [15]:
torch.cat([a]*6,3)


tensor([[[[ 3.0000,  3.0000,  3.0000,  3.0000,  3.0000,  3.0000],
          [ 4.0000,  4.0000,  4.0000,  4.0000,  4.0000,  4.0000],
          [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
          [ 3.0000,  3.0000,  3.0000,  3.0000,  3.0000,  3.0000],
          [ 3.0000,  3.0000,  3.0000,  3.0000,  3.0000,  3.0000],
          [ 2.0000,  2.0000,  2.0000,  2.0000,  2.0000,  2.0000]]],


        [[[ 3.0000,  3.0000,  3.0000,  3.0000,  3.0000,  3.0000],
          [ 4.0000,  4.0000,  4.0000,  4.0000,  4.0000,  4.0000],
          [ 3.5000,  3.5000,  3.5000,  3.5000,  3.5000,  3.5000],
          [ 3.0000,  3.0000,  3.0000,  3.0000,  3.0000,  3.0000],
          [ 3.0000,  3.0000,  3.0000,  3.0000,  3.0000,  3.0000],
          [ 2.0000,  2.0000,  2.0000,  2.0000,  2.0000,  2.0000]]]])

In [16]:
b

NameError: name 'b' is not defined

In [17]:
torch.cat([b]*6,2)


NameError: name 'b' is not defined

In [ ]:
torch.cat([a]*6,3)+torch.cat([b]*6,2)


In [7]:
class E2EBlock(torch.nn.Module):
    '''E2Eblock.'''

    def __init__(self, in_planes, planes,example,bias=True):
        super(E2EBlock, self).__init__()
        self.d = example.size(3)
        self.cnn1 = torch.nn.Conv2d(in_planes,planes,(1,self.d),bias=bias)
        self.cnn2 = torch.nn.Conv2d(in_planes,planes,(self.d,1),bias=bias)

        
    def forward(self, x):
        a = self.cnn1(x)
        b = self.cnn2(x)
        return torch.cat([a]*self.d,3)+torch.cat([b]*self.d,2)



In [13]:
block = E2EBlock(1,1,input_torch,False)
block(Variable(input_torch))

tensor([[[[ 0.4799,  1.2642,  1.1106,  0.9420,  0.5945,  1.0179],
          [ 0.0978,  0.8821,  0.7285,  0.5599,  0.2124,  0.6358],
          [-0.5087,  0.2756,  0.1221, -0.0465, -0.3941,  0.0293],
          [ 0.1739,  0.9582,  0.8047,  0.6360,  0.2885,  0.7119],
          [ 0.2946,  1.0789,  0.9253,  0.7567,  0.4092,  0.8326],
          [-0.4521,  0.3322,  0.1786,  0.0100, -0.3375,  0.0859]]],


        [[[ 0.4799,  1.2642,  1.1106,  0.9420,  0.5945,  1.0179],
          [ 0.0978,  0.8821,  0.7285,  0.5599,  0.2124,  0.6358],
          [-0.5087,  0.2756,  0.1221, -0.0465, -0.3941,  0.0293],
          [ 0.1739,  0.9582,  0.8047,  0.6360,  0.2885,  0.7119],
          [ 0.2946,  1.0789,  0.9253,  0.7567,  0.4092,  0.8326],
          [-0.4521,  0.3322,  0.1786,  0.0100, -0.3375,  0.0859]]]])

BrainNetCNN Network for fitting Gold-MSI on LSD dataset

In [89]:
"""" KERAS MODEL 
model.add(E2E_conv(2,32,(2,n_feat),kernel_regularizer=reg,input_shape=(n_feat,n_feat,1),input_dtype='float32',data_format="channels_last"))
print("First layer output shape :"+str(model.output_shape))
model.add(LeakyReLU(alpha=0.33))
#print(model.output_shape)
model.add(E2E_conv(2,32,(2,n_feat),kernel_regularizer=reg,data_format="channels_last"))
print(model.output_shape)
model.add(LeakyReLU(alpha=0.33))
model.add(Convolution2D(64,(1,n_feat),kernel_regularizer=reg,data_format="channels_last"))
model.add(LeakyReLU(alpha=0.33))
model.add(Convolution2D(256,(n_feat,1),kernel_regularizer=reg,data_format="channels_last"))
model.add(LeakyReLU(alpha=0.33))
#print(model.output_shape)
model.add(Dropout(0.5))


model.add(Dense(128,kernel_regularizer=reg,kernel_initializer=kernel_init))
#print(model.output_shape)
model.add(LeakyReLU(alpha=0.33))
#print(model.output_shape)
model.add(Dropout(0.5))
model.add(Dense(30,kernel_regularizer=reg,kernel_initializer=kernel_init))
model.add(LeakyReLU(alpha=0.33))
#print(model.output_shape)
model.add(Dropout(0.5))
model.add(Dense(2,kernel_regularizer=reg,kernel_initializer=kernel_init))
model.add(Flatten())
model.add(LeakyReLU(alpha=0.33))
""""

class BrainNetCNN(torch.nn.Module):
    def __init__(self, example, num_classes=10):
        super(BrainNetCNN, self).__init__()
        self.in_planes = example.size(1)
        self.d = example.size(3)
        
        self.e2econv1 = E2EBlock(1,32,example)
        self.e2econv2 = E2EBlock(32,64,example)
        self.E2N = torch.nn.Conv2d(64,1,(1,self.d))
        self.N2G = torch.nn.Conv2d(1,256,(self.d,1))
        self.dense1 = torch.nn.Linear(256,128)
        self.dense2 = torch.nn.Linear(128,30)
        self.dense3 = torch.nn.Linear(30,2)

    def forward(self, x):
        out = F.leaky_relu(self.e2econv1(x),negative_slope=0.33)
        out = F.leaky_relu(self.e2econv2(out),negative_slope=0.33) 
        out = F.leaky_relu(self.E2N(out),negative_slope=0.33)
        out = F.dropout(F.leaky_relu(self.N2G(out),negative_slope=0.33),p=0.5)
        out = out.view(out.size(0), -1)
        out = F.dropout(F.leaky_relu(self.dense1(out),negative_slope=0.33),p=0.5)
        out = F.dropout(F.leaky_relu(self.dense2(out),negative_slope=0.33),p=0.5)
        out = F.leaky_relu(self.dense3(out),negative_slope=0.33)
        
        return out


In [134]:
net = BrainNetCNN(input_torch)
net(Variable(input_torch))

tensor(1.00000e-02 *
       [[-6.1536,  5.9549],
        [-6.1536,  5.9549]])

In [152]:
input_torch.size()

torch.Size([2, 1, 6, 6])

refs : carlos , voir [ici](https://github.com/brain-bzh/MCNN/blob/master/proposed/pines_aux.py) et [ici](https://github.com/brain-bzh/MCNN/blob/master/proposed/cifar.py)


Loader for GoldMSI-LSD77 dataset

In [161]:
behavdir = "/Users/nicolasfarrugia/Documents/recherche/git/Gold-MSI-LSD77/behav"

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import os

import torch.utils.data.dataset

class GoldMSI_LSD_Dataset(torch.utils.data.Dataset):

    def __init__(self, directory=behavdir,mode="train",transform=False,class_balancing=False):
        """
        Args:
            directory (string): Path to the dataset.
            mode (str): train = 90% Train, validation=10% Train, train+validation=100% train else test.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.directory = directory
        self.mode = mode
        self.transform = transform
 
        x = np.load(os.path.join(directory,"X_y_lsd77_static_tangent.npz"))['X']
        y_all = np.load(os.path.join(directory,"X_y_lsd77_static_tangent.npz"))['y']            
        y_2=y_all[:,[3,4]]
        y = normalize(y_2,axis=0)
        
        X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33)
        
        if self.mode=="train":
            
            x = X_train
            y = y_train
            
        elif self.mode=="validation":
            x = X_test
            y = y_test
        elif mode=="train+validation":
            x=x
            y=y
        else:
            x=x
            y=y
            
            
        self.X = torch.FloatTensor(np.expand_dims(x,1).astype(np.float32))
        #self.X = torch.FloatTensor(x.astype(np.float32))
        self.Y = torch.FloatTensor(y.astype(np.float32))
         
        print(self.mode,self.X.shape,(self.Y.shape))
            
    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        sample = [self.X[idx], self.Y[idx]]
        if self.transform:
            sample[0] = self.transform(sample[0])
        return sample

In [162]:
trainset = GoldMSI_LSD_Dataset(mode="train")
trainloader = torch.utils.data.DataLoader(trainset, batch_size=14, shuffle=True, num_workers=1)

testset = GoldMSI_LSD_Dataset(mode="validation")
testloader = torch.utils.data.DataLoader(testset, batch_size=14, shuffle=False, num_workers=1)

train torch.Size([203, 1, 64, 64]) torch.Size([203, 2])
validation torch.Size([101, 1, 64, 64]) torch.Size([101, 2])


Training

In [130]:
"""" KERAS 

opt = optimizers.SGD(momentum=momentum,nesterov=True,lr=lr)
model.compile(optimizer=opt,loss='mean_squared_error',metrics=['mae'])

csv_logger = callbacks.CSVLogger('BrainCNN_gmsi.log')

history=model.fit(X_train,y_train,epochs=1000,verbose=1,callbacks=[csv_logger])

""""

SyntaxError: EOL while scanning string literal (<ipython-input-130-39670bbd93c3>, line 10)

In [163]:
net = BrainNetCNN(trainset.X)

momentum = 0.9
lr = 0.01

criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(net.parameters(),lr=lr,momentum=momentum,nesterov=True)


In [167]:
def train(epoch):
    net.train()
    train_loss = 0
    correct = 0
    total = 0
    
    for batch_idx, (inputs, targets) in enumerate(trainloader):
        
        #if use_cuda:
        #    inputs, targets = inputs.cuda(), targets.cuda()
        
        optimizer.zero_grad()
        inputs, targets = Variable(inputs), Variable(targets)
        outputs = net(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        train_loss += loss.data[0]
        
        print(loss.data[0])
        #_, predicted = torch.max(outputs.data, 1)
        
        #total += targets.size(0)
        
        #correct += predicted.eq(targets.data).cpu().sum()


def test():
    net.eval()
    test_loss = 0
    correct = 0
    total = 0
    for batch_idx, (inputs, targets) in enumerate(testloader):
        
        #if use_cuda:
        #    inputs, targets = inputs.cuda(), targets.cuda()
        
        inputs, targets = Variable(inputs, volatile=True), Variable(targets)
        
        outputs = net(inputs)
        loss = criterion(outputs, targets)

        test_loss += loss.data[0]
        
        print(loss.data[0])
        
        #_, predicted = torch.max(outputs.data, 1)
        #total += targets.size(0)
        #correct += predicted.eq(targets.data).cpu().sum()

    # Save checkpoint.
    #acc = 100.*correct/total
    return test_loss.mean()


In [168]:
nbepochs = 5

for epoch in range(nbepochs):
    train(epoch)
    acc = test()
    last_acc = acc

/Users/nicolasfarrugia/miniconda3/envs/eeg/lib/python3.6/site-packages/ipykernel_launcher.py:19: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
/Users/nicolasfarrugia/miniconda3/envs/eeg/lib/python3.6/site-packages/ipykernel_launcher.py:21: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


tensor(1.00000e-03 *
       4.5860)
tensor(1.00000e-03 *
       3.9852)
tensor(1.00000e-03 *
       3.3321)
tensor(1.00000e-03 *
       2.8694)
tensor(1.00000e-03 *
       3.7924)
tensor(1.00000e-03 *
       2.7636)
tensor(1.00000e-03 *
       4.1660)
tensor(1.00000e-03 *
       2.4515)
tensor(1.00000e-03 *
       2.6980)
tensor(1.00000e-03 *
       2.2797)
tensor(1.00000e-03 *
       3.1827)
tensor(1.00000e-03 *
       2.1142)
tensor(1.00000e-03 *
       1.6463)
tensor(1.00000e-03 *
       1.4550)
tensor(1.00000e-03 *
       1.1643)


/Users/nicolasfarrugia/miniconda3/envs/eeg/lib/python3.6/site-packages/ipykernel_launcher.py:39: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
/Users/nicolasfarrugia/miniconda3/envs/eeg/lib/python3.6/site-packages/ipykernel_launcher.py:44: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
/Users/nicolasfarrugia/miniconda3/envs/eeg/lib/python3.6/site-packages/ipykernel_launcher.py:46: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


tensor(1.00000e-03 *
       1.4185)
tensor(1.00000e-03 *
       1.5979)
tensor(1.00000e-04 *
       9.7864)
tensor(1.00000e-03 *
       1.1636)
tensor(1.00000e-03 *
       1.8211)
tensor(1.00000e-03 *
       1.0433)
tensor(1.00000e-03 *
       1.5735)
tensor(1.00000e-04 *
       9.2852)


NameError: name 'best_acc' is not defined

In [166]:
acc

tensor(1.00000e-02 *
       3.1542)